# Generated by Django 4.2.1 on 2023-05-28 18:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, unique=True
            ),
        ),
    ]
