# Generated by Django 4.2.1 on 2023-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places_api", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["geom"], name="places_api__geom_fcce54_idx"),
        ),
    ]
